### ISSUE TITLE
주문하기 메인 페이지 구현 

### ISSUE THREAD

**Issue by SeungJooKim** [codals/greating#120]
## Feature Description
- 주문하기 메인 페이지 프론트 구현 

## Todo list

- [x] 주문하기 메인 페이지 구현
- [x] 주문하기 페이지와 링크 연결 
- [x] 주문하기 버튼이 아래 하단에 계속 따라다니게 하기
