### ISSUE TITLE
각종 예외 처리 및 리팩토링

### ISSUE THREAD

**Issue by signature-hyeon** [codals/greating#128]
## Feature Description
- 각종 예외 처리 및 리팩토링

## Todo list

- [x] 로그인시 어드민 헤더 변경
- [x] 로그인한 유저시 로그인, 회원가입 페이지 접근 불가
- [x] 주문 세션 없을시 다른 페이지 렌더링
- [x] result 페이지를 경로에 드러내지 않고 세션에 값 저장
- [x] header.referer 제거
- [ ] 주문 페이지 정보 넘기
