### ISSUE TITLE
DIY 상세페이지 2차 구현

### ISSUE THREAD

**Issue by SeungJooKim** [codals/greating#135]
## Feature Description
- 관련 포스팅 정보 추가
- 관련 건강마켓 상품 추가
- 프론트 깨짐 수정

## Todo list

- [x] 서브카테고리 기준으로 연관 포스팅 가져오기
- [x] 건강 마켓 상품 랜덤하게 가져오기 
- [x] 연관 포스팅 정보 띄울 프론트 구현하기
- [x] 건강 마켓 상품 띄울 프론트 구현하기 
- [x] 상세보기 페이지 tab 작동하도록 수정
