### ISSUE TITLE
[Front + Back] 코드 정리

### ISSUE THREAD

**Issue by deingvelop** [codals/greating#157]
## Feature Description
- 

## Todo list

- [x] 필요 없는 import 정리
- [ ] log.info 정리
- [ ] console.log 정리
- [ ] 주석처리된 필요없는 코드, 필요 없는 Class 정리
