### ISSUE TITLE
캐시 관련 이슈 해결 및 front 자잘한 수정

### ISSUE THREAD

**Issue by deingvelop** [codals/greating#179]
## Feature Description
- 

## Todo list

- [x] 등록시 캐시 관련 코드 제거
- [x] 검색시 페이지 이동에서 alert 뜨는 거 제거
- [x] 로그인으로 리다이렉트될 때 alert 뜨게 변경
- [x] Youtube 로고 바꾸기
