### ISSUE TITLE
Front components 구현

### ISSUE THREAD

**Issue by deingvelop** [codals/greating#2]
## Feature Description
- [x] 상단 검색 header
- [x] 카테고리 팝업
- [x] 로그인 전 상단 배너
- [x] 로그인 후 상단 배너

## Todo list

- [x] `jsp`에 `html` 효율적으로 import 할 수 있도록 설정
- [x] 프로젝트 파일 구조 초기 설계

**Comment by deingvelop** [comment]
### `header.jsp` import하는 방법

👉🏻 body 태그 내에 다음의 코드를 넣는다.
```jsp
<!-- header 가져오기 -->
<jsp:include page="templates/header.jsp"/>
```

#### 활용 예시
```jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Home</title>
	</head>
	<body>
		<!-- header 가져오기 -->
   		<jsp:include page="templates/header.jsp"/>
		<h1>
			Hello world!  
		</h1>
		
		<P>  The time on the server is ${serverTime}. </P>
	</body>
</html>
```
