### ISSUE TITLE
Front components & 화면 구현 

### ISSUE THREAD

**Issue by SeungJooKim** [codals/greating#3]
## Feature Description
 - [x] 메인화면 구현 
 - [x] 회원가입 시작페이지 구현
 - [x] footer 구현

## Todo list
- [x] 메인화면 슬라이드 추가 ( 3개 ) 
- [x] 메인화면 애니메이션 추가 ( 잔잔하게 뜨게 하기 ) 
- [x] 회원가입 시작 페이지 구현 
- [x] footer 구현 ( 파일 분리 - 다른 파일들과 연결 시 깨지지 않는지 확인 ) 

- [x] jsp안에 header / footer html 깨지지 않게 삽입하기 
- [x] 이미지 , 정적 파일 폴더 분리
