### ISSUE TITLE
프론트 전반 코드 / 디자인 수정 

### ISSUE THREAD

**Issue by SeungJooKim** [codals/greating#38]
## Feature Description
1.  식단 검색 페이지 
- [x] 검색 바 정렬 / 식단별로 보기 간격 조정 필요
- [x] 페이지 카테고리 달기

2. 메인페이지
- [x] 상단 배너 바 크기 조정 필요
- [x] 애니메이션 속도 조절 필요

3. 마이페이지 - 사이드 바 
- [x] 회원 탈퇴 추가

4. 로그인 
- [?] 로그인 크기 재조정 

5. footer
- [x] footer 간격 조정 

6. 모든 페이지
- [x] 페이지 카테고리 + hr 수정

7. 마이페이지 전체
- [x] footer깨짐 수정

## Todo list

- [ ]
