### ISSUE TITLE
DIY 식단 상세 조회 기능 

### ISSUE THREAD

**Issue by SeungJooKim** [codals/greating#52]
## Feature Description
- 식단 상세 조회 기능 구현하기

## Todo list

- [x] 상세페이지 로드 
- [x] 밥 / 국 /  메인 / 사이드  정보 food 테이블 참조해서 모두 가져와야 함. 
- [x] user 정보도 가져올 것
- [x] 투표 여부에 따라 투표 기능 
- [x] 스크랩 여부에 따라 스크랩 기능

**Comment by SeungJooKim** [comment]
투표에 해당하는 Database 테이블 이름 변경하는 것이 좋을 거 같음 : like -> vote
