### ISSUE TITLE
DIY 식단 등록하기 기능 구현

### ISSUE THREAD

**Issue by deingvelop** [codals/greating#53]
## Feature Description
- DIY 식단 등록하기

## Todo list
- [x] DIY 식단 등록하기 페이지 로드
- [x] DIY 식단 등록하기 POST 요청

### 3차 구현
- [ ] 모달창에서 사이드를 선택하면 2개 이상 선택되는 이슈 해결
- [ ] 모달창에서 사이드를 선택하면 null값으로 들어오는 이슈 해결
- [ ] 사이드, 메인, 국, 밥 중 필수로 할 것들 지정 및 required, javascript 문제 해결
- [ ] 이미지를 resources/images/uploaded에 저장하기

### 추가 기능
- [ ] DIY 식단 등록하기 - 건강마켓 검색 및 모달창 관련 기능 구현
