### ISSUE TITLE
exception 초기 설정

### ISSUE THREAD

**Issue by deingvelop** [codals/greating#6]
## Feature Description
- 예외처리를 쉽게 하기 위한 초기 설정

## Todo list

- [ ] 예외 처리 방법 정리
- [ ] HandlerExceptionResolver 구현해서 CustomExceptionHandler 만들기
- [ ] ErrorCode 정리
- [ ] error.jsp 페이지 꾸미기
- [ ] RuntimeException 상속 받아 BusinessException 만들기
- [ ] alert 관련 설정
