### ISSUE TITLE
DIY 식단 등록 페이지 &  DIY 식단 리스트 페이지 구현

### ISSUE THREAD

**Issue by SeungJooKim** [codals/greating#8]
## Feature Description
- [x] DIY 식단 등록 페이지
- [x] DIY 식단 리스트 페이지
- [x] DIY TOP 10 페이지 구현

## Todo list
- [x] DIY 식단 등록 페이지 스크롤로 각 반찬들 뜨게 구현하기
- [x] DIY 식단 등록 페이지 모달 창 ( 건강마켓 ) 구현하기
- [x] DIY 식단 등록 기타 정보 띄우는 란 모두 구현
- [x] DIY 식단 TOP 10 페이지 슬라이더 넣어서 구현하기 
- [x] DIY 식단 관련 페이지에 모두 쓸수있는 카드 형식 구현하기 

- [x] 폴더 diy로 분리하기
- [x] header / footer 연결해보고 수정
