### ISSUE TITLE
백엔드-프론트 연결 ( 투표하기  / 스크랩 )  

### ISSUE THREAD

**Issue by SeungJooKim** [codals/greating#88]
## Feature Description
- 투표하기 / 투표 취소하기 기능 프론트와 연결
- 스크랩 / 스크랩 취소하기 기능 프론트와 연결

## Todo list

- [x] 투표하기 기능 백엔드 - 프론트 연결
- [x] 투표하기 기능 이미 투표한 이력이 있는지 백엔드 기능 필요 ( 상세 페이지 띄울 때 )
- [x] 투표 여부에 따라 상세페이지 다르게 띄우기 
- [x] 투표한 후에 프론트 버튼 바꾸기  ( ajax ) 

- [x] 스크랩하기 기능 백엔드 - 프론트와 연결 
- [x] 스크랩 이력이 있는지 백엔드 기능 필요
- [x] 스크랩 여부에 따라 상세페이지 다르게 띄우기
- [x] 스크랩 후에 프론트 버튼 바꾸기
