### ISSUE TITLE
DIY 등록하기 페이지 수정

### ISSUE THREAD

**Issue by deingvelop** [codals/greating#93]
## Feature Description
- 프론트 자잘한 수정
- 모달창 관련 수정

## Todo list
- [x] 사이드 모달창에서 또 2개를 고를 수 있는 문제 수정
- [x] 최대 칼로리/가격이 최소 칼로리/가격보다 작아도 되는 문제 수정
- [x] 건강마켓에서 선택하면, 선택한 항목 이름이 뜨게 수정
- [x] required인 항목들은 안 적으면 표시나 animation 창이 뜨게 수정
- [x] 사진을 입력하지 않으면 디폴트 이미지로 되도록 수정
